### ISSUE TITLE
ui问题

### ISSUE THREAD

**Issue by GinMu** [JCCDex/jingtumMask#1]
1. 中英文混杂
![image](https://user-images.githubusercontent.com/12183493/63067682-b102ac80-bf42-11e9-9d91-59f297eb742d.png)

2. ui问题
![image](https://user-images.githubusercontent.com/12183493/63067702-c8da3080-bf42-11e9-86c8-4623585fcb5f.png)
![image](https://user-images.githubusercontent.com/12183493/63067708-cf68a800-bf42-11e9-9c32-925e97a1ebe6.png)

3. 转账和挂单作为不可逆操作，应该有确认过程，而不是点击next后就立即进行
![image](https://user-images.githubusercontent.com/12183493/63067730-e9a28600-bf42-11e9-900b-7818dab98df5.png)

4. 导入新秘钥后，获取余额失败
![image](https://user-images.githubusercontent.com/12183493/63067753-05a62780-bf43-11e9-84e0-c5bdf3884799.png)
![image](https://user-images.githubusercontent.com/12183493/63067756-0c349f00-bf43-11e9-813c-da118433abf5.png)

**Comment by GinMu** [comment]
1. 修改钱包名称失败
![image](https://user-images.githubusercontent.com/12183493/63068123-a6491700-bf44-11e9-8e49-005f71ec934c.png)

**Comment by luozb** [comment]
已修复

**Comment by luozb** [comment]
> 1. 中英文混杂
>    ![image](https://user-images.githubusercontent.com/12183493/63067682-b102ac80-bf42-11e9-9d91-59f297eb742d.png)
> 2. ui问题
>    ![image](https://user-images.githubusercontent.com/12183493/63067702-c8da3080-bf42-11e9-86c8-4623585fcb5f.png)
>    ![image](https://user-images.githubusercontent.com/12183493/63067708-cf68a800-bf42-11e9-9c32-925e97a1ebe6.png)
> 3. 转账和挂单作为不可逆操作，应该有确认过程，而不是点击next后就立即进行
>    ![image](https://user-images.githubusercontent.com/12183493/63067730-e9a28600-bf42-11e9-900b-7818dab98df5.png)
> 4. 导入新秘钥后，获取余额失败
>    ![image](https://user-images.githubusercontent.com/12183493/63067753-05a62780-bf43-11e9-84e0-c5bdf3884799.png)
>    ![image](https://user-images.githubusercontent.com/12183493/63067756-0c349f00-bf43-11e9-813c-da118433abf5.png)

问题已修复

**Comment by GinMu** [comment]
冻结数量最好能超出自动换行显示，不然数量大还是会存在ui问题
